Feature/ran login implementation
i-v-FSD/springTraining pull request #20
Opened 2024-01-12 10:00 UTC by iVinci-KenichiRan

## やったこと

- spring securityを使用した認証機能、ユーザー登録機能の実装

    - 対象資産
       - conterllers/UserController.java
       - services/LoginUserService.java
       - dao/LoginUserDao.java
       - securingweb/LoginUserDetails.java
       - securingweb/LoginUserDetailsService.java
       - securingweb/WebSecurityConfig.java
       - Entity/UserForm.java
       - templates/login.html
       - templates/signup.html
       - ※上記全て新規作成
    
    - 資産ごとの作成内容
        - conterllers/UserController.java
            - 認証機能、ユーザー登録機能共有のコントローラ
                - ログイン画面の表示
                - サインアップ画面の表示
                - サインアップ処理のハンドリング
                - ログアウト処理のハンドリング
                - ※ログイン処理はspring securityの機能がハンドリングしてくれるため、こちらでの記載は不要
        
        - services/LoginUserService.java
            - ユーザー登録機能で使用するサービスクラス
                - ユーザー登録処理でコントローラから受け取ったユーザー情報を受け取り、パスワードをハッシュ化させてDaoを呼び出す処理を作成
        
        - dao/LoginUserDao.java
            - 認証機能、ユーザー登録機能共有のDaoクラス
                - 認証機能でemail情報を元にDBよりユーザー情報を取得(findUser)を作成
                - ユーザー登録機能でユーザー情報をDBに登録(createUser)を作成

        - securingweb/LoginUserDetails.java
            - 認証機能で使用するEntityクラス
                - LoginUserDao.javeで取得したユーザー情報を格納する処理を作成
                    - ※spring securityのUserDetailsインターフェースの実装クラス

        - securingweb/LoginUserDetailsService.java
            - 認証機能で使用するサービスクラス
                - フォームから送られてきたemailをLoginUserDao.javaに渡しユーザー情報を取得する処理を作成
                    - ※spring securityのUserDetailsServiceインターフェースの実装クラス

        - securingweb/WebSecurityConfig.java
            - 認証機能の設定ファイル
                - 認証不要のページ、ログインフォームの設定処理（securityFilterChain）を作成
                - パスワードのハッシュ化設定(PasswordEncoder)
                    - ハッシュの種類は公式のチュートリアルで使用していたBCryptを使用

        - Entity/UserForm.java
            - ユーザー登録機能で使用するEntityクラス
                - 画面からフォームでユーザー情報を受け取る
                - バリデーションはアノテーションを使用
                    - ※バリデーションついてはとりあえずつけておりますので、このバリデーションが必要等あればご指摘ください。

        - templates/login.html
            - ログイン画面

        - templates/signup.html
            - サインアップ画面           

## やってないこと

- 各画面のCSS適応
- ユーザー登録時のemailが重複した際のハンドリング処理（すみません、手が回りませんでした）
- 認証機能での権限設定(ボリュームが大きくなりすぎると思い一旦実装してません。)
- ログインしたユーザーのIDを取得する処理
    - こちらは下記でコントローラから取得できることは確認できました。（コントローラーで取得して画面に渡す）これで問題なければTweetコントローラに追加をしたいと思っております。（他にいい方法あればお教えください。→cookieに入れ込むなど）
 ```
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        LoginUserDetails userInfo =(LoginUserDetails) authentication.getPrincipal();
```

- 各テンプレートのログアウト遷移処理反映
    - 下記のように"/logout"に遷移するとセッションがクリアさせますが、各テンプレートに反映はしておりません
    ```<a href="#" th:href="@{/logout}" th:attr="data-method='post'">ログアウト</a>```
    
## 確認してほしいこと

- 実装に問題がないか

- spring securityのお作法に反していないか
    - 今回の実装で参考にして資料
        - https://spring.pleiades.io/guides/gs/securing-web/ (公式ドキュメント)
        - https://www.docswell.com/s/MasatoshiTada/KGVY9K-spring-security-intro#p36　(spring bootに詳しい方の説明資料)
        - https://qiita.com/suke_masa/items/908805dd45df08ba28d8 (spring securityのバージョンアップにより大幅な変更点をまとめてあるQiita記事)

- 現状のコードとの統一感があるか

- 新人の方が実装できるのか

2024-01-12 14:07 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/TopController.java
> +
不要な修正ですね

2024-01-12 14:09 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/UserController.java
> +    private LoginUserService loginUserService;
CRUDの方に合わせて、コンストラクタインジェクションで統一しましょう
https://github.com/i-v-FSD/springTraining/pull/16#discussion_r1448240859

2024-01-12 14:12 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/signup.html";
```suggestion
        return "signup";
```

2024-01-12 14:12 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login";
```suggestion
        return "login";
```

2024-01-12 14:13 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login.html";
```suggestion
         return "login";
```

2024-01-12 14:13 UTC, iVinci-KentaroARIMA commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login";
```suggestion
         return "login";
```

2024-01-15 07:43 UTC, iVinci-AkitoYOSHIMURA requested changes
チーム内での方針が見えないため、少しだけコメントつけるにとどめています。
方針が見えたら、再度レビューします。

2024-01-15 07:43 UTC, iVinci-AkitoYOSHIMURA commented on src/main/java/com/example/tweet/dao/LoginUserDao.java
> +        String sql = "SELECT id, email,name,password FROM user WHERE email = ?;";
```suggestion
        String sql = "SELECT id, email, name, password FROM user WHERE email = ?;";
```

2024-01-15 07:43 UTC, iVinci-AkitoYOSHIMURA commented on src/main/java/com/example/tweet/entities/UserForm.java
> +    @Size(max=20 ,message = "名前は２０文字以内で入力してください。")
```suggestion
    @Size(max=20 ,message = "名前は20文字以内で入力してください。")
```
半角、全角はメッセージ内で統一お願いします。

2024-01-15 07:43 UTC, iVinci-AkitoYOSHIMURA commented on src/main/java/com/example/tweet/entities/LoginUser.java
JPAを使うかどうか、チーム内で認識合わせお願いします。

2024-01-16 09:22 UTC, iVinci-KentaroARIMA requested changes

2024-01-16 09:22 UTC, iVinci-KentaroARIMA commented on src/main/resources/templates/login.html
> +    </form>
サインアップ画面（/signup）へのリンクを追加してください。
初回アクセス時はユーザ作成が必要ですが、現状サインアップ画面への導線がありません。

2024-01-16 09:28 UTC, iVinci-KentaroARIMA commented
動確したところ、下記の不具合があったため修正をお願いします。
→サインイン後のTOP画面遷移時にエラーになる。
　（[http://localhost:8080/](http://localhost:8080/)　を手入力するとTOP画面に遷移可）

![image](https://github.com/i-v-FSD/springTraining/assets/42313362/79cda6e4-67b3-4170-92d2-6f8458ca9122)

2024-01-16 09:31 UTC, iVinci-KentaroARIMA commented on src/main/resources/templates/signup.html
> +        <input type="email" id="password" th:field="*{password}" />
現状、パスワードに対してメールアドレスのチェックが適用されてしまいエラーになります
![image](https://github.com/i-v-FSD/springTraining/assets/42313362/cfdade8f-83c3-476d-b16d-2c17357f7d5a)

2024-01-17 04:20 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/services/LoginUserService.java
> +    private PasswordEncoder passwordEncoder;
コンストラクタインジェクションに修正いたしました。
6ca7375

2024-01-17 04:21 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/securingweb/LoginUserDetailsService.java
> +    public LoginUserDao loginUserDao;
コンストラクタインジェクションに修正いたしました。
6ca7375

2024-01-17 04:21 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/dao/LoginUserDao.java
> +    private JdbcTemplate jdbc;
コンストラクタインジェクションに修正いたしました。
6ca7375

2024-01-17 04:27 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/signup.html";
修正いたしました。
ce4d4d2

2024-01-17 04:27 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login";
修正いたしました。
ce4d4d2

2024-01-17 04:28 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login.html";
修正いたしました。
ce4d4d2

2024-01-17 04:28 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/controllers/UserController.java
> +        return "/login";
修正いたしました。
ce4d4d2

2024-01-17 04:28 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/controllers/UserController.java
> +            return "/signup.html";
修正いたしました。
ce4d4d2

2024-01-17 08:49 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/securingweb/WebSecurityConfig.java
> +    public PasswordEncoder PasswordEncoder() {
小文字に修正しました。
acd6c95

2024-01-17 08:50 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/entities/UserForm.java
> +    private String email;
修正いたしました。
c71752c

2024-01-17 08:51 UTC, iVinci-KenichiRan commented on src/main/java/com/example/tweet/entities/LoginUser.java
> +    }
lombokを使用するように修正しました。

c71752c

2024-01-18 04:21 UTC, iVinci-KenichiRan commented
下記のMTGにより認証機能はカリキュラムに反映させてない方針となったため、本プルリクはクローズします。
[Loop:20230119 第8回](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL3ZpbmNpMDEuc2hhcmVwb2ludC5jb20vP25hdj1jejBsTWtZbVpEMWlJVGhrT0ZOTlozVTNYMVZQWDJGamVUY3pUamR0TWtoT1lucDZRa04wZHpsRWNERjJRelJ5U0Zaa2RUVTRZMnR1Y1U4MlFtdFJTakZWYVZBNVEyNUNhVTBtWmowd01VUlJXRUpKVUZsUE0xWXlRalkzVmt3M05VUkxTRkpDVWtoYVJFSkdVa0ZhSm1NOUptWnNkV2xrUFRFJTNEIiwiciI6ZmFsc2V9LCJwIjp7InUiOiJodHRwczovL3ZpbmNpMDEuc2hhcmVwb2ludC5jb20vOmZsOi9yL2NvbnRlbnRzdG9yYWdlL0NTUF8zMjEyZGZmMS1iYjBiLTQzZmQtYmY2OS1jY2JiZGNkZWU2ZDgvJUUzJTgzJTg5JUUzJTgyJUFEJUUzJTgzJUE1JUUzJTgzJUExJUUzJTgzJUIzJUUzJTgzJTg4JTIwJUUzJTgzJUE5JUUzJTgyJUE0JUUzJTgzJTk2JUUzJTgzJUE5JUUzJTgzJUFBL0xvb3BBcHBEYXRhLyVFNyU4NCVBMSVFOSVBMSU4Qy5sb29wP2Q9dzFhNjFmMTU2MGRlNzRiN2NiYzU3OGExZTljNjE5YTU1JmNzZj0xJndlYj0xJm5hdj1jejBsTWtaamIyNTBaVzUwYzNSdmNtRm5aU1V5UmtOVFVGOHpNakV5WkdabU1TMWlZakJpTFRRelptUXRZbVkyT1MxalkySmlaR05rWldVMlpEZ21aRDFpSVRoa09GTk5aM1UzWDFWUFgyRmplVGN6VGpkdE1raE9ZbnA2UWtOMGR6bEVjREYyUXpSeVNGWmtkVFU0WTJ0dWNVODJRbXRSU2pGVmFWQTVRMjVDYVUwbVpqMHdNVVJSV0VKSlVESlhOa1pSVWxaYVdVNVFVa1l6V1ZZMFMwUXlUMGRFUjFOV0ptTTlKVEpHSm1ac2RXbGtQVEVtWVQxTWIyOXdRWEJ3Sm5BOUpUUXdabXgxYVdSNEpUSkdiRzl2Y0Mxd1lXZGxMV052Ym5SaGFXNWxjaVo0UFNVM1FpVXlNbmNsTWpJbE0wRWxNakpVTUZKVVZVaDRNbUZYTldwaFZFRjRURzVPYjFsWVNteGpSemx3WW01UmRWa3lPWFJtUjBsb1QwZFJORlV3TVc1a1ZHUm1WbFU1WmxsWFRqVk9lazVQVGpJd2VWTkZOV2xsYm5CRFVUTlNNMDlWVW5kTldGcEVUa2hLU1ZadFVqRk9WR2hxWVRJMWVGUjZXa05oTVVaTFRWWldjRlZFYkVSaWEwcHdWRmgzZDAxVlVsSlhSVXBLVlVac1VFMHhXWGxSYWxrelZtdDNNMDVWVWt4VFJrcERWV3RvWVZKRlNrZFZhMFpoSlRJeUpUSkRKVEl5YVNVeU1pVXpRU1V5TWpJMU5qY3hOV0ZrTFRJME5qa3ROR0kwTXkxaE5EbGpMVEkxWVRJek1ETm1ZVE0yTWlVeU1pVTNSQSUzRCUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiMjU2NzE1YWQtMjQ2OS00YjQzLWE0OWMtMjVhMjMwM2ZhMzYyIn19)

2024-01-18 04:21 UTC, closed without merging