テーブル定義修正
i-v-FSD/springTraining pull request #9
Opened 2023-11-22 10:22 UTC by iVinci-KenichiRan

## やったこと

- ログイン機能追加によりテーブル定義を変更

## やってないこと

- 実装の変更

## 確認してほしいこと

- テーブル定義に漏れがないか

2023-11-24 00:08 UTC, iVinci-AkitoYOSHIMURA commented on mysql/init/insert_data.sql
> +    `user` (id, name, email, password)
元が悪いのですが、ドメインを`@example.com`にしてもらえますか？
参考：https://qiita.com/suzutsuki0220/items/4ad83ed2e2adbb6507a4

2023-11-24 00:24 UTC, iVinci-AkitoYOSHIMURA requested changes
PRの本文の記載が薄く、本対応の妥当性が判断できないため、初期データのみ確認してコメントを付けています。

前提や経緯がわかる様に残してください。

```mardown
今回、ユーザー登録、ログイン、ログアウト機能を追加することになったため、userテーブルの定義を変更しました。
- ログインは`email`、`password`で行います
  - `email`がキーになるため、ユニークで定義しています
```

※上記は例として挙げているため、実際には詳細に記載お願いします。
※ウォーターフォール型のプロジェクトなら、インプットとなるドキュメント（要件定義書、仕様書など）がありますよね？それと同じです。

2023-11-24 00:24 UTC, iVinci-AkitoYOSHIMURA commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
```suggestion
    ("1", '山田 太郎','Taro.Yamada@example.com', 'pass123');
```
元が悪いのですが、ドメインを`@example.com`にしてもらえますか？
参考：https://qiita.com/suzutsuki0220/items/4ad83ed2e2adbb6507a4

2023-11-24 00:24 UTC, iVinci-AkitoYOSHIMURA commented on mysql/init/insert_data.sql
> +    ("4", '鈴木',"suzuki@fuga.com", 'Hello Tweet');
`tweet`テーブルの初期値が無くなりますが、問題ないですか？
また`password`に`Hello Tweet`は意図していますか？
今後、実装するユーザー登録でパスワードに記号（スペース）を許可するかどうかにはねると思われるため、確認です。

2023-11-28 07:47 UTC, iVinci-KentaroARIMA commented on docs/architecture.md
tweetテーブルのuser_idは外部キーとして定義しましょう。

2023-11-28 08:16 UTC, iVinci-KentaroARIMA commented on docs/architecture.md
>  |id|MEDIUMINT|yes|AUTO_INCREMENT|yes|
せっかくSpringSecurityで認証機構作るので、ついでにidも数値のインクリメントではなくUUID生成する形にしましょう。

2023-12-04 00:12 UTC, iVinci-RyosukeMISHIMA commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
nameカラムのvalueとカンマの後にスペースがあると可読性が上がると思います。（以降のINSERT文も同様）

2023-12-06 06:01 UTC, iVinci-KenichiRan commented on docs/architecture.md
>  |create_at|TIMESTAMP||CURRENT_TIMESTAMP||
@iVinci-RyosukeMISHIMA 
ご指摘の通りですので、"created_at"に修正いたしました。
95f6759

2023-12-11 23:54 UTC, iVinci-KenichiRan commented on docs/architecture.md
外部キーとして定義しました。
ca071d8

2023-12-12 00:05 UTC, iVinci-KenichiRan commented on mysql/init/insert_data.sql
> +    ("4", '鈴木',"suzuki@fuga.com", 'Hello Tweet');
@iVinci-AkitoYOSHIMURA 
tweetテーブルの初期値は欲しいので、再定義しました。
passwordにHello Tweetは意図しておりませんでしたので、削除しました。
2764184

2023-12-12 00:06 UTC, iVinci-KenichiRan commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
@iVinci-AkitoYOSHIMURA 
`@example.com`に修正しております。

2023-12-12 00:15 UTC, iVinci-KenichiRan commented on docs/architecture.md
>  |id|MEDIUMINT|yes|AUTO_INCREMENT|yes|
@iVinci-KentaroARIMA 
実装の際に修正は検討させていただきます。

2023-12-12 00:21 UTC, akiyoshi1989 commented on mysql/init/insert_data.sql
> +    ("4", '鈴木',"suzuki@fuga.com", 'Hello Tweet');
@iVinci-KenichiRan 
`'` と`"`が混在しているのが気になります。統一しましょう。

2023-12-12 00:22 UTC, iVinci-AkitoYOSHIMURA commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
@iVinci-KenichiRan 
`'` と`"`が混在しているのが気になります。統一しましょう。
※これも元が悪い

2023-12-12 01:58 UTC, iVinci-KentaroARIMA approved these changes

2023-12-13 02:54 UTC, iVinci-KenichiRan commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
ご指摘の通りですので、スペースを追加しました。
80058bc

2023-12-13 02:55 UTC, iVinci-KenichiRan commented on mysql/init/insert_data.sql
> +    ("1", '山田','hoge@fuga.com', 'pass123');
@iVinci-AkitoYOSHIMURA 
クォーテーションを統一しました。
80058bc

2023-12-13 05:03 UTC, iVinci-RyosukeMISHIMA approved these changes

2023-12-13 06:51 UTC, merged